### ISSUE TITLE
Application hang when calling panic

### ISSUE THREAD

**Issue by timmattison** [charmbracelet/bubbletea#904] opened 2024-01-17 16:34 UTC
**Describe the bug**
I have gotten my application to hang in a way that I can't get out of it without killing it from another terminal when calling panic while the application is initializing. If the application panics at a later time it exits properly.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS - macOS Sonoma 14.2.1
 - Shell - zsh
 - Terminal Emulator - iterm2
 - Terminal Multiplexer - N/A

**To Reproduce**
1. Clone https://github.com/timmattison/bubbletea-hang
2. Run `go run main2.go model.go`
3. Kill the process from another terminal

**Source Code**
Source code is in linked repo

**Expected behavior**
I would expect that it panics and exits but instead gets stuck when trying to write to the done channel.
 https://github.com/charmbracelet/bubbletea/blob/8f3464a75600e991bbce22229d6e5b99975416f0/standard_renderer.go#L121

**Comment by timmattison** [comment] 2024-01-17 20:38
I think #905 should fix this but I haven't had enough time to test it. Can anyone take a look and see what you think?

**Comment by muesli** [comment] 2024-03-01 17:22
Closing as dupe of #924.

**Closed by muesli** 2024-03-01 17:22 UTC
