### ISSUE TITLE
Mouse scroll doesn't work in foot terminal

### ISSUE THREAD

**Issue by ibrokemypie** [charmbracelet/bubbletea#149] opened 2021-11-02 13:17 UTC
In the [foot](https://gitlab.com/dnkl/foot) terminal mouse scroll events aren't triggered at all (though other mouse events trigger okay). Mouse scrolling works in other terminals such as alacritty so I don't think the issue is with my code, and other programs such as htop have working mouse scrolling support in foot making me think the issue is on bubbletea's side

**Comment by ibrokemypie** [comment] 2021-11-02 15:15
Cell motion, though I also have tried all motion and that doesnt work either

**Comment by meowgorithm** [comment] 2021-11-02 17:30
I'm able to detect mouse wheel events when running the [mouse example](https://github.com/charmbracelet/bubbletea/tree/master/examples/mouse) in Foot.

Perhaps the issue is in your code? I'd be happy to take a look if you'd like.

**Comment by ibrokemypie** [comment] 2021-11-03 06:01
Sure, the code in question is [here](https://github.com/ibrokemypie/kwatch/blob/master/kwatch.go), I just assumed the code was fine because it was quite simple and works in every other terminal I have tried :P

**Comment by bashbunni** [comment] 2022-09-09 18:06
Hey @ibrokemypie please let us know if this is still an issue for you otherwise I'll close this issue

**Comment by muesli** [comment] 2022-10-04 04:25
I can't reproduce this (at least anymore) in foot. Closing, but feel free to comment if this is still an issue for you.

**Closed by muesli** 2022-10-04 04:25 UTC
Labels: question
