### ISSUE TITLE
textinput only takes the first char with IME

### ISSUE THREAD

**Issue by Zym3Gen** [charmbracelet/bubbletea#20] opened 2020-10-26 01:42 UTC
e.g. with the example textinput component:

while typing:
![image](https://user-images.githubusercontent.com/71834886/97125632-795ed980-176f-11eb-83d6-5c4ed64efa1d.png)

actually got:
![image](https://user-images.githubusercontent.com/71834886/97125645-84b20500-176f-11eb-9011-2579f1cbb6ef.png)

**Comment by meowgorithm** [comment] 2020-10-26 01:54
Thanks for the report. Which operating system are you running?

**Comment by Zym3Gen** [comment] 2020-10-26 10:23
Oh, sorry to mention: it's on macOS 10.15.7 (19H2). And the terminal is iTerm2 Build 3.3.12.

**Comment by meowgorithm** [comment] 2020-10-26 13:44
Thanks! Also, what are the exact input settings you're using?

**Comment by Zym3Gen** [comment] 2020-10-27 02:23
I use [Sogou Pinyin IME](http://pinyin.sogou.com/), a popular one among Chinese users.

The program I tested is an example you provided: https://github.com/charmbracelet/bubbletea/blob/master/examples/textinput/main.go

**Comment by mritd** [comment] 2020-10-29 04:45
The same problem under [Rime IME](https://rime.im/)

![image](https://user-images.githubusercontent.com/13043245/97526438-1629ad00-19e4-11eb-862c-a8b6755d9ad8.png)

There are also problems under the Mac native IME

![image](https://user-images.githubusercontent.com/13043245/97526647-89332380-19e4-11eb-8441-f28abd808664.png)

**Comment by Obsidian6s** [comment] 2020-10-29 05:48
Broken with Apple Default SC Pinyin IME as well:

![image](https://user-images.githubusercontent.com/72505240/97530507-432e8d80-19ed-11eb-992b-c896ec5dea9b.png)

![image](https://user-images.githubusercontent.com/72505240/97530539-55103080-19ed-11eb-95ce-d98986067855.png)

**Comment by mritd** [comment] 2020-10-29 11:33
After checking the code, the problem seems to be caused by the [readInput](https://github.com/charmbracelet/bubbletea/blob/1e0283511e94c492a99c22f77374405d1e8dfd6a/key.go#L282) method in `key.go`. The utf8.DecodeRune method always decodes the first rune, causing subsequent data loss.

But I don’t understand the specific logic and how to fix it.

**Comment by meowgorithm** [comment] 2020-10-29 12:58
This is all very helpful; thank you for all the reports. It's really important to us that we sort this one out — I'll keep this thread updated with progress.

**Comment by meowgorithm** [comment] 2020-10-30 04:05
Hi everyone. Just a note that we're implementing a fix for this and expect to have it merged in the next few days. We'll continue to keep this thread updated with progress.

**Closed** 2020-11-01 13:57 UTC
Labels: bug

**Comment by meowgorithm** [comment] 2020-11-01 14:03
Hi everyone! Just a note that this is fixed in `master`. We'll be doing releases on Bubble Tea and Bubbles tomorrow that will contain this fix.

Thanks again for flagging this, and let us know if you have anymore trouble with IME.
