### ISSUE TITLE
WithOutput should receive an io.Writer

### ISSUE THREAD

**Issue by campoy** [charmbracelet/bubbletea#66] opened 2021-03-11 01:42 UTC
Currently, [WithOutput](https://pkg.go.dev/github.com/charmbracelet/bubbletea#WithOutput) receives an `*os.File` which makes it harder to write tests.

I do not see any reason for this not to be changed, as the `output` field in `Program` is already an `io.Writer`.

PS: I'm loving this library! ❤️

**Comment by meowgorithm** [comment] 2021-03-11 01:48
Thank you for the kind words! And yep, you're totally right. @kiyonlin just flagged this one the other day and is planning on fixing it. We can track progress and move discussion over there.

(Duplicate of #63)

**Closed by meowgorithm** 2021-03-11 01:48 UTC

**Comment by meowgorithm** [comment] 2021-03-11 01:52
Ha, actually @kiyonlin already fixed this and it's ready to go in `master`, it just hasn't been tagged in a version yet. We'll do a release soon but in the meantime feel free to pin against `master`.

Cheers!

**Comment by meowgorithm** [comment] 2021-03-11 22:14
Just a heads up, @campoy, that this is now available in Bubble Tea v0.13.0.
