### ISSUE TITLE
could not decode rune

### ISSUE THREAD

**Issue by muesli** [charmbracelet/bubbletea#668] opened 2023-02-16 11:36 UTC
### Discussed in https://github.com/charmbracelet/bubbletea/discussions/664

<div type='discussions-op-text'>

<sup>Originally posted by **mschneider82** December  5, 2022</sup>
i am using the mouse input and always getting a program exit after a while because of "could not decode rune"

I would expect it continues instead of failing on a invalid utf 8 rune.

```
		r, width := utf8.DecodeRune(b[i:])
		if r == utf8.RuneError {
			return nil, errors.New("could not decode rune")
		}
```</div>

**Comment by muesli** [comment] 2023-02-16 11:37
Note: the reason we return an error here, is that this is a bit of a panic situation, as all further decodes would likely fail to.

On the bright side, I believe this is already fixed by @knz and I will soon get to merge that fix.

**Comment by j178** [comment] 2023-03-24 07:01
Hi,

I encountered the same problem, here is a minimal reproduction example:
```go
package main

import (
	"log"

	tea "github.com/charmbracelet/bubbletea"
)

type model struct{}

func (model) Init() tea.Cmd {
	return nil
}

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	return m, nil
}

func (model) View() string {
	return "hello world"
}

func main() {
	p := tea.NewProgram(model{})
	log.Fatal(p.Run())
}
```

When running the program, if you paste below text to the terminal, the program will exit with "could not decode rune" error:
```
我要你扮演一个侏儒。你会为我提供可以在任何地方进行的活动和爱好的有趣、独特的想法。例如，我可能会向您询问有趣的院子设计建议或在天气不佳时在室内消磨时间的创造性方法。此外，如有必要，您可以建议与我的要求相符的其他相关活动或项目。我的第一个请求是“我正在寻找我所在地区的新户外活动"
```

Actually this bug can be reproduced in any bubbletea program, if any Chinese text longer than 256 characters is pasted, the program will exit.

**Comment by knz** [comment] 2023-03-24 08:10
Yep, this is a known issue.

@muesli my PR to handle long inputs should help alleviate this.

**Comment by j178** [comment] 2024-01-02 10:07
Since https://github.com/charmbracelet/bubbletea/pull/570 gets merged, I think this issue is resolved now.

**Closed** 2024-03-01 17:11 UTC
Labels: bug
